owner: 'Hannes Schaller'
year: '2020'
title: cyberkov.at
author:
    name: 'Hannes Schaller'
    email: admin@cyberkov.at
    url: 'https://cyberkov.at' # the base hostname & protocol for your site, e.g. http://example.com
    twitter: cyberkov
tagline: Aus dem Leben gegriffen
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://cyberkov.at'

social:
    links:
        - https://twitter.com/cyberkov
        - https://github.com/cyberkov
        - https://keybase.io/cyberkov
        - https://www.xing.com/profile/Hannes_Schaller2
        - https://www.facebook.com/cyberkov
        - http://at.linkedin.com/in/cyberkov/

# Build settings
theme: jekyll-theme-hacker
plugins:
    - jekyll-deploy
    - jekyll-feed
    - jekyll-maps
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-responsive-image
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-umlauts

source: source
picture:
    source: images/

permalink: /:year/:month/:day/:title/
timezone: Europe/Vienna
encoding: utf-8
locale: de_at

future: true

paginate: 10 # Posts per page on the blog index
paginate_path: /page/:num/
excerpt_link: 'Read on &rarr;' # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: '<!--more-->'

titlecase: true # Converts page and post titles to titlecase

deploy:
    - rsync -vaz --delete ./ easyname:/data/web/e11256/html/cyberkov.at/www/

maps:
    google:
        api_key: AIzaSyBezinwrPOcICgU8EJFtv6wghEGnAyu9rA
        marker_cluster:
            enabled: false

responsive_image:
    #base_path: source/assets
    template: _includes/srcset.html
    sizes:
        - width: 320
        - width: 480
        - width: 800

# Build settings
defaults:
    - scope:
          path: '_posts'
          type: 'posts'
      values:
          published: true
          layout: 'post'
          category:
          author:
          tags: []
          summary:
